/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro.pizzarest;

//import com.mycompany.pizzeriaproject.Customer;
//import com.mycompany.pizzeriaproject.Customer_1;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class CustomerGUI extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public CustomerGUI() {
        initComponents();
        
     setImage();

    }

    public void setImage(){
        ImageIcon icon1 =new ImageIcon(getClass().getResource("/images/pizza1.jpg"));
                Image img1 =icon1.getImage().getScaledInstance(image1.getWidth(), image1.getHeight(), Image.SCALE_SMOOTH);
        image1.setIcon(new ImageIcon(img1));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnAddCustomer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaAllCust = new javax.swing.JTextArea();
        jbtnShowAllCust = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        jbtnEdit = new javax.swing.JButton();
        jbtnPlaceOrder = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtCustID = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jtxtPhoneNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jbtnAddCustomer.setBackground(new java.awt.Color(255, 153, 102));
        jbtnAddCustomer.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnAddCustomer.setText("Add new customer");
        jbtnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddCustomerActionPerformed(evt);
            }
        });

        jtxtAreaAllCust.setColumns(20);
        jtxtAreaAllCust.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaAllCust);

        jbtnShowAllCust.setBackground(new java.awt.Color(255, 204, 153));
        jbtnShowAllCust.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnShowAllCust.setText("Show all customers");
        jbtnShowAllCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowAllCustActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(204, 204, 204));
        jbtnBack.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnClose.setBackground(new java.awt.Color(204, 204, 204));
        jbtnClose.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnClose.setText("Close");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jbtnEdit.setBackground(new java.awt.Color(204, 204, 204));
        jbtnEdit.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnEdit.setText("Edit");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnPlaceOrder.setBackground(new java.awt.Color(255, 153, 102));
        jbtnPlaceOrder.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnPlaceOrder.setText("Place An Order");
        jbtnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlaceOrderActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(153, 51, 0));
        label1.setText("Customer Information Sysytem");

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel2.setText("Name");

        jLabel1.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel1.setText("CustomerID");

        jLabel3.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel3.setText("PhoneNumber");

        jtxtCustID.setBackground(new java.awt.Color(204, 204, 204));
        jtxtCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCustIDActionPerformed(evt);
            }
        });

        jtxtName.setBackground(new java.awt.Color(204, 204, 204));

        jtxtPhoneNo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jtxtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnBack)
                                .addGap(257, 257, 257)
                                .addComponent(jbtnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnAddCustomer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jbtnShowAllCust)
                                        .addGap(123, 123, 123)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnShowAllCust, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddCustomerActionPerformed
try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un="hala";
            String up="123456";
            Connection con= DriverManager.getConnection(custr, un, up);
            con.setAutoCommit(false);
            Statement stmt=con.createStatement();
            String CID=this.jtxtCustID.getText();
            String Name=this.jtxtName.getText();           
            String phNo=this.jtxtPhoneNo.getText();
            
          //  String add=this.jtxtAddress.getText();
          String strStmt = "INSERT INTO Customer VALUES ('" 
           + CID + "', '" 
           + Name + "', '" 
           + phNo + "')";
            stmt.executeUpdate(strStmt);
            con.commit();
            con.close();
            
        } catch (Exception ex) {
           // Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, ex.toString());
           
        }

    }//GEN-LAST:event_jbtnAddCustomerActionPerformed

    private void jbtnShowAllCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowAllCustActionPerformed
  try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un="hala";
            String up="123456";
            Connection con= DriverManager.getConnection(custr, un, up);
            String sqlStr="select * from Customer";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(sqlStr);
            this.jtxtAreaAllCust.setText("Cust ID\tName\tPhone No\tAddress \n ");
           while( rs.next()){
              String cid= rs.getString(1);
              String cn= rs.getString(2);
              String phno= rs.getString(3);
            //  String email= rs.getString(4);
              String add= rs.getString(4);
              this.jtxtAreaAllCust.append(cid+"\t"+ cn +"\t"+phno+"\t"+add+"\n");
           }                           
            con.close();
            
        } catch (Exception ex) {
           // Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, ex.toString());
           
        }
    }//GEN-LAST:event_jbtnShowAllCustActionPerformed

    private void jtxtCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCustIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCustIDActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        HomePage2 hp = new HomePage2();
        hp.setVisible(true);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        // TODO add your handling code here:
       try {
        // Register the PostgreSQL driver and connect to the database
        DriverManager.registerDriver(new org.postgresql.Driver());
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "hala";
        String up = "123456";
        Connection con = DriverManager.getConnection(custr, un, up);
        con.setAutoCommit(false);

        // Get the updated values from text fields
        String CID = this.jtxtCustID.getText();
        String Name = this.jtxtName.getText();           
        String phNo = this.jtxtPhoneNo.getText();
        //String mail = this.jtxtEmail.getText();
        //String add = this.jtxtAddress.getText();

        // SQL update statement with parameters, using quotes for case-sensitive column names
       String strStmt = "UPDATE Customer SET \"Name\" = ?, \"phonenumber\" = ? WHERE \"customerid\" = ?";

        // Use PreparedStatement to prevent SQL injection
        PreparedStatement pstmt = con.prepareStatement(strStmt);
        pstmt.setString(1, Name);
        pstmt.setString(2, phNo);
        pstmt.setInt(3, Integer.parseInt(CID));

        // Execute the update statement
        int rowsAffected = pstmt.executeUpdate();
        con.commit();
        
        // Close the connection
        pstmt.close();
        con.close();

        // Check if the update was successful
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Customer updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Customer ID not found.");
        }
        
    } catch (Exception ex) {
        // Show error message in case of an exception
        JOptionPane.showMessageDialog(null, ex.toString());
    }
    }//GEN-LAST:event_jbtnEditActionPerformed

    private void jbtnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlaceOrderActionPerformed
        // TODO add your handling code here:
        OrderGUI poGUI =new OrderGUI();
        poGUI.show();
        dispose();
    }//GEN-LAST:event_jbtnPlaceOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAddCustomer;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnPlaceOrder;
    private javax.swing.JButton jbtnShowAllCust;
    private javax.swing.JTextArea jtxtAreaAllCust;
    private javax.swing.JTextField jtxtCustID;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPhoneNo;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
