/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro.pizzarest;

//import com.mycompany.pizzeriaproject.HomePage;
//import com.mycompany.pizzeriaproject.HomePage;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pro.pizzarest.HomePage2;

/**
 *
 * @author Hala Shakaa4
 */
public class DeliveryGUI extends javax.swing.JFrame {
 
     public DeliveryGUI() {
        initComponents();
        setImage();
    }

    
    public void setImage(){

         ImageIcon icon2 =new ImageIcon(getClass().getResource("/images/deli.jpg"));
         ImageIcon icon3 =new ImageIcon(getClass().getResource("/images/pizza1.jpg"));

        Image img2 =icon2.getImage().getScaledInstance(image1.getWidth(), image1.getHeight(), Image.SCALE_SMOOTH);

                Image img3 =icon3.getImage().getScaledInstance(image2.getWidth(), image2.getHeight(), Image.SCALE_SMOOTH);

        
        
        image1.setIcon(new ImageIcon(img2));
                       image2.setIcon(new ImageIcon(img3));
 

    }
    /**
     * Creates new form DeliveryGUI
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtDeliveryID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtOrderID = new javax.swing.JTextField();
        jtxtDelTime = new javax.swing.JTextField();
        jComboBoxDelStatus = new javax.swing.JComboBox<>();
        jbtnAddDelivery = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAllDeliv = new javax.swing.JTextArea();
        jbtnShowDeliv = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jbtnBack = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtdeliveryID = new javax.swing.JTextField();
        image2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel1.setText("Delivery ID :");

        jLabel2.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel2.setText("Order ID :");

        jLabel4.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel4.setText("Delivery Time :");

        jLabel5.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel5.setText("Delivery Status :");

        jtxtOrderID.setBackground(new java.awt.Color(255, 204, 153));

        jtxtDelTime.setBackground(new java.awt.Color(255, 204, 153));

        jComboBoxDelStatus.setBackground(new java.awt.Color(255, 204, 153));
        jComboBoxDelStatus.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jComboBoxDelStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On the Way", "Delivered" }));

        jbtnAddDelivery.setBackground(new java.awt.Color(255, 153, 102));
        jbtnAddDelivery.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtnAddDelivery.setText("Add New Delivery");
        jbtnAddDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddDeliveryActionPerformed(evt);
            }
        });

        jTextAreaAllDeliv.setBackground(new java.awt.Color(255, 204, 153));
        jTextAreaAllDeliv.setColumns(20);
        jTextAreaAllDeliv.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAllDeliv);

        jbtnShowDeliv.setBackground(new java.awt.Color(255, 153, 102));
        jbtnShowDeliv.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtnShowDeliv.setText("Show All Deliveries");
        jbtnShowDeliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowDelivActionPerformed(evt);
            }
        });

        jbtnDelete.setBackground(new java.awt.Color(255, 153, 102));
        jbtnDelete.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("All Deliveries :");

        jbtnBack.setBackground(new java.awt.Color(204, 204, 204));
        jbtnBack.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtnBack.setText("Go Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnClose.setBackground(new java.awt.Color(204, 204, 204));
        jbtnClose.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtnClose.setText("Close");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("Delivey Information System");

        jtxtdeliveryID.setBackground(new java.awt.Color(255, 204, 153));
        jtxtdeliveryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdeliveryIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnBack)
                    .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxDelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtDelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtdeliveryID, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtnShowDeliv)
                                .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnAddDelivery)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(237, 237, 237)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtdeliveryID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtDelTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxDelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnAddDelivery)
                            .addComponent(jLabel6))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnShowDeliv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jbtnDelete)
                .addGap(31, 31, 31)
                .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        HomePage2 hp = new HomePage2();
        hp.setVisible(true);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void jbtnShowDelivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowDelivActionPerformed

  // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un="hala";
            String up="123456";
            Connection con= DriverManager.getConnection(custr, un, up);
            String sqlStr="select * from Delivery";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(sqlStr);
            this.jTextAreaAllDeliv.setText("DeliveryID\tOrderID\tDeliveryPersonID\tDeliveryTime\t\t DeliveryStatus \n ");
           while( rs.next()){
              String did= rs.getString(1);
              String oid= rs.getString(2);
              String pid= rs.getString(3);
              String dtime= rs.getString(4);
              String delst= rs.getString(5);
            
               this.jTextAreaAllDeliv.append(did + "\t" + oid + "\t" + pid + "\t\t" + dtime +"\t"+delst+ "\n");
           }                           
            con.close();
            
        } catch (Exception ex) {
           // Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, ex.toString());
           
        }

    }//GEN-LAST:event_jbtnShowDelivActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
   // TODO add your handling code here:
        try {
        // Register the PostgreSQL driver
        DriverManager.registerDriver(new org.postgresql.Driver());
        
        // Database connection details
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "hala";
        String up = "123456";
        
        // Establish a connection
        Connection con = DriverManager.getConnection(custr, un, up);
        
        // Get the Employee ID to delete
        String DID = this.jtxtdeliveryID.getText();
        
        // Check if EID is not empty
        if (DID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter an Delivery ID.");
            return;
        }

        // Prepare and execute the DELETE statement
        String strStmt = "DELETE FROM Delivery WHERE DeliveryID = ?";
        PreparedStatement pstmt = con.prepareStatement(strStmt);
        pstmt.setInt(1, Integer.parseInt(DID)); // Set the EmployeeID in the SQL statement
        
        // Execute the delete and get the result
        int rowsAffected = pstmt.executeUpdate();
        
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Delivey deleted successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "No Delivey found with ID: " + DID);
        }
        
        // Close the connection
        con.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.toString());
    }


    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnAddDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddDeliveryActionPerformed

  try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un="hala";
            String up="123456";
            Connection con= DriverManager.getConnection(custr, un, up);
            con.setAutoCommit(false);
            Statement stmt=con.createStatement();
            String DID=this.jtxtdeliveryID.getText();
            String oid=this.jtxtOrderID.getText();
      //      String perid=this.jtxtDelPersonID.getText();
            String deltime=this.jtxtDelTime.getText();
           String Status = (String) jComboBoxDelStatus.getSelectedItem();

         String strStmt = "INSERT INTO Delivery (OrderID, DeliveryPersonID, \"DeliveryTime\", \"DeliveryStatus\") VALUES ('" 
    + oid + "', '302', '" 
    
    + deltime + "', '" 
    + Status + "')";
            stmt.executeUpdate(strStmt);
            con.commit();
            con.close();
            
        } catch (Exception ex) {
           // Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, ex.toString());
           
        }
        
        

    }//GEN-LAST:event_jbtnAddDeliveryActionPerformed

    private void jtxtdeliveryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdeliveryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdeliveryIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JComboBox<String> jComboBoxDelStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAllDeliv;
    private javax.swing.JButton jbtnAddDelivery;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnShowDeliv;
    private javax.swing.JTextField jtxtDelTime;
    private javax.swing.JTextField jtxtDeliveryID;
    private javax.swing.JTextField jtxtOrderID;
    private javax.swing.JTextField jtxtdeliveryID;
    // End of variables declaration//GEN-END:variables
}
