/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro.pizzarest;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import pro.pizzarest.HomePage2;



/**
 *
 * @author Hala Shakaa4
 */
public class EmployeeGUI extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeGUI
     */
    public EmployeeGUI() {
        initComponents();
                setImage();

    }

    public void setImage(){
        ImageIcon icon1 =new ImageIcon(getClass().getResource("/images/pizza1.jpg"));
                Image img1 =icon1.getImage().getScaledInstance(image1.getWidth(), image1.getHeight(), Image.SCALE_SMOOTH);
        image1.setIcon(new ImageIcon(img1));
    }
        
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jbtnAddEmployee = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaAllEmp = new javax.swing.JTextArea();
        jbtnShowAllEmployees = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtempID = new javax.swing.JTextField();
        jtxtFName = new javax.swing.JTextField();
        jtxtLName = new javax.swing.JTextField();
        jtxtRole = new javax.swing.JTextField();
        jtxtPhoneNo = new javax.swing.JTextField();
        jtxtHireDate = new javax.swing.JTextField();
        jtxtSalary = new javax.swing.JTextField();
        jbtnEdit = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnAddEmployee.setBackground(new java.awt.Color(255, 204, 153));
        jbtnAddEmployee.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jbtnAddEmployee.setText("Add New Employee");
        jbtnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddEmployeeActionPerformed(evt);
            }
        });

        jtxtAreaAllEmp.setColumns(20);
        jtxtAreaAllEmp.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaAllEmp);

        jbtnShowAllEmployees.setBackground(new java.awt.Color(255, 204, 153));
        jbtnShowAllEmployees.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jbtnShowAllEmployees.setText("Show All Employees");
        jbtnShowAllEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowAllEmployeesActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("EMPLOYEE INFORMATION SYSTEM");

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("Employee ID :");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Last Name :");

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Role :");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number :");

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Hire Date :");

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("Salary :");

        jtxtempID.setBackground(new java.awt.Color(204, 204, 204));
        jtxtempID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jtxtFName.setBackground(new java.awt.Color(204, 204, 204));
        jtxtFName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jtxtLName.setBackground(new java.awt.Color(204, 204, 204));
        jtxtLName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtxtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLNameActionPerformed(evt);
            }
        });

        jtxtRole.setBackground(new java.awt.Color(204, 204, 204));
        jtxtRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jtxtPhoneNo.setBackground(new java.awt.Color(204, 204, 204));
        jtxtPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jtxtHireDate.setBackground(new java.awt.Color(204, 204, 204));
        jtxtHireDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jtxtSalary.setBackground(new java.awt.Color(204, 204, 204));
        jtxtSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtFName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addComponent(jtxtempID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtLName))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtHireDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addComponent(jtxtPhoneNo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtxtRole)
                        .addComponent(jtxtSalary, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtempID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtHireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jbtnEdit.setBackground(new java.awt.Color(255, 204, 153));
        jbtnEdit.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jbtnEdit.setText("Edit");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnDelete.setBackground(new java.awt.Color(255, 204, 153));
        jbtnDelete.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(204, 204, 204));
        jbtnBack.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jbtnBack.setText("Go back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setText("Generate Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnShowAllEmployees)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnAddEmployee)
                        .addGap(49, 49, 49)
                        .addComponent(jbtnEdit)
                        .addGap(54, 54, 54)
                        .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 322, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnAddEmployee)
                            .addComponent(jbtnShowAllEmployees)
                            .addComponent(jbtnEdit)
                            .addComponent(jbtnDelete)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLNameActionPerformed

    private void jbtnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddEmployeeActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un="hala";
            String up="123456";
            Connection con= DriverManager.getConnection(custr, un, up);
            con.setAutoCommit(false);
            Statement stmt=con.createStatement();
            String EID=this.jtxtempID.getText();
            String fName=this.jtxtFName.getText();
            String lName=this.jtxtLName.getText();
            String role=this.jtxtRole.getText();
            String phNo=this.jtxtPhoneNo.getText();
            String hDate=this.jtxtHireDate.getText();
            String sal=this.jtxtSalary.getText();
            String strStmt = "INSERT INTO Employee VALUES (" 
    + EID + ", '" 
    + fName + "', '" 
    + lName + "', '" 
    + role + "', '" 
    + phNo + "', '" 
    + hDate + "', " 
    + sal + ")";
           // String strStmt="insert into Employee values(" + EID + ", " + fName + ", '" + lName + "', '" + role + "', '" + phNo + "', " + hDate+"', '"+ sal + ")";
            stmt.executeUpdate(strStmt);
            con.commit();
            con.close();
            
        } catch (Exception ex) {
           // Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, ex.toString());
           
        }
        
        
        
    }//GEN-LAST:event_jbtnAddEmployeeActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        //close();
        dispose();
        HomePage2 hp = new HomePage2();
        hp.setVisible(true);
        
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
        try {
        // Register the PostgreSQL driver
        DriverManager.registerDriver(new org.postgresql.Driver());
        
        // Database connection details
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "hala";
        String up = "123456";
        
        // Establish a connection
        Connection con = DriverManager.getConnection(custr, un, up);
        
        // Get the Employee ID to delete
        String EID = this.jtxtempID.getText();
        
        // Check if EID is not empty
        if (EID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter an Employee ID.");
            return;
        }

        // Prepare and execute the DELETE statement
        String strStmt = "DELETE FROM Employee WHERE EmployeeID = ?";
        PreparedStatement pstmt = con.prepareStatement(strStmt);
        pstmt.setInt(1, Integer.parseInt(EID)); // Set the EmployeeID in the SQL statement
        
        // Execute the delete and get the result
        int rowsAffected = pstmt.executeUpdate();
        
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Employee deleted successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "No employee found with ID: " + EID);
        }
        
        // Close the connection
        con.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.toString());
    }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        // TODO add your handling code here:
           try {
        // Register the PostgreSQL driver and connect to the database
        DriverManager.registerDriver(new org.postgresql.Driver());
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "hala";
        String up = "123456";
        Connection con = DriverManager.getConnection(custr, un, up);
        con.setAutoCommit(false);

        // Retrieve updated values from the text fields
        String EID = this.jtxtempID.getText();
        String fName = this.jtxtFName.getText();
        String lName = this.jtxtLName.getText();
        String role = this.jtxtRole.getText();
        String phNo = this.jtxtPhoneNo.getText();
        String hDate = this.jtxtHireDate.getText();
        String sal = this.jtxtSalary.getText();

        // SQL update statement using parameterized query to prevent SQL injection
        String strStmt = "UPDATE Employee SET \"FName\" = ?, \"LName\" = ?, \"Role\" = ?, \"PhoneNumber\" = ?, \"HireDate\" = ?, \"Salary\" = ? WHERE \"employeeid\" = ?";

        // Use PreparedStatement to set parameters
        PreparedStatement pstmt = con.prepareStatement(strStmt);
        pstmt.setString(1, fName);
        pstmt.setString(2, lName);
        pstmt.setString(3, role);
        pstmt.setString(4, phNo);
        pstmt.setDate(5, java.sql.Date.valueOf(hDate)); // Convert to SQL Date
        pstmt.setBigDecimal(6, new BigDecimal(sal)); // Convert to BigDecimal for Salary
        pstmt.setInt(7, Integer.parseInt(EID));

        // Execute the update statement
        int rowsAffected = pstmt.executeUpdate();
        con.commit();
        
        // Close the connection
        pstmt.close();
        con.close();

        // Check if the update was successful
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Employee updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Employee ID not found.");
        }
        
    } catch (Exception ex) {
        // Show error message in case of an exception
        JOptionPane.showMessageDialog(null, ex.toString());
    }
    }//GEN-LAST:event_jbtnEditActionPerformed

    private void jbtnShowAllEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowAllEmployeesActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un="hala";
            String up="123456";
            Connection con= DriverManager.getConnection(custr, un, up);
            String sqlStr="select * from Employee";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(sqlStr);
            this.jtxtAreaAllEmp.setText("Emp ID\tF_Name\tL_Name\tRole\tPhone No\tHire Date\tSalary \n ");
           while( rs.next()){
              String eid= rs.getString(1);
              String fn= rs.getString(2);
              String ln= rs.getString(3);
              String role= rs.getString(4);
              String phno= rs.getString(5);
              String hd= rs.getString(6);
              String sal= rs.getString(7);
               this.jtxtAreaAllEmp.append(eid + "\t" + fn + "\t" + ln + "\t" + role + "\t" + phno + "\t" + hd + "\t" + sal + "\n");
           }                           
            con.close();
            
        } catch (Exception ex) {
           // Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, ex.toString());
           
        }
        
    }//GEN-LAST:event_jbtnShowAllEmployeesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        try{
     DriverManager.registerDriver(new org.postgresql.Driver());
            String url= "jdbc:postgresql://localhost:5432/postgres";
            String user="hala";
            String password="123456";
            Connection con= DriverManager.getConnection(url, user, password);
            InputStream inp= new FileInputStream(new File("EmployeesRole.jrxml"));
            JasperDesign jd= JRXmlLoader.load(inp);
            JasperReport jr= JasperCompileManager.compileReport(jd);
            JasperPrint jp= JasperFillManager.fillReport(jr, null, con);
  //        OutputStream os= new FileOutputStream(new File("rep.pdf"));
  //        JasperExportManager.exportReportToPdfStream(jp, os);
  //        os.close();
            JFrame frame = new JFrame("report");  
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);          
            con.close();
            inp.close();
            
        } catch (Exception ex) {
            //Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.toString());
        }    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton jbtnAddEmployee;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnShowAllEmployees;
    private javax.swing.JTextArea jtxtAreaAllEmp;
    private javax.swing.JTextField jtxtFName;
    private javax.swing.JTextField jtxtHireDate;
    private javax.swing.JTextField jtxtLName;
    private javax.swing.JTextField jtxtPhoneNo;
    private javax.swing.JTextField jtxtRole;
    private javax.swing.JTextField jtxtSalary;
    private javax.swing.JTextField jtxtempID;
    // End of variables declaration//GEN-END:variables
}
