/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro.pizzarest;

import java.awt.Image;
import javax.swing.ImageIcon;
import pro.pizzarest.CustomerGUI;


/**
 *
 * @author Admin
 */
public class HomePage2 extends javax.swing.JFrame {

    /**
     * Creates new form HomePage2
     */
    public HomePage2() {
        initComponents();
        
        
        setImage();
    }
    public void setImage(){

         ImageIcon icon1 =new ImageIcon(getClass().getResource("/images/pizza2.jpg"));
         ImageIcon icon2 =new ImageIcon(getClass().getResource("/images/homep.jpg"));
         ImageIcon icon3 =new ImageIcon(getClass().getResource("/images/pizza8.jpg"));

        Image img1 =icon1.getImage().getScaledInstance(image2.getWidth(), image2.getHeight(), Image.SCALE_SMOOTH);
        Image img2 =icon2.getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
        Image img3 =icon3.getImage().getScaledInstance(image6.getWidth(), image6.getHeight(), Image.SCALE_SMOOTH);

        
        
        
        image2.setIcon(new ImageIcon(img1));
        image.setIcon(new ImageIcon(img2));
        image6.setIcon(new ImageIcon(img3));
      

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        image2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbtnOrders = new javax.swing.JButton();
        jbtnEmployees = new javax.swing.JButton();
        jbtnCustomers = new javax.swing.JButton();
        jbtnDeliv = new javax.swing.JButton();
        jbtnPizzaMENU = new javax.swing.JButton();
        image6 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230), 4));

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230), 4));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pizzeria Resturant Home Page");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));

        jbtnOrders.setBackground(new java.awt.Color(204, 204, 204));
        jbtnOrders.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jbtnOrders.setText("Orders");
        jbtnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrdersActionPerformed(evt);
            }
        });

        jbtnEmployees.setBackground(new java.awt.Color(204, 204, 204));
        jbtnEmployees.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jbtnEmployees.setText("Employees");
        jbtnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmployeesActionPerformed(evt);
            }
        });

        jbtnCustomers.setBackground(new java.awt.Color(204, 204, 204));
        jbtnCustomers.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jbtnCustomers.setText("Customers");
        jbtnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCustomersActionPerformed(evt);
            }
        });

        jbtnDeliv.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDeliv.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jbtnDeliv.setText("Deliveries");
        jbtnDeliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDelivActionPerformed(evt);
            }
        });

        jbtnPizzaMENU.setBackground(new java.awt.Color(204, 204, 204));
        jbtnPizzaMENU.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jbtnPizzaMENU.setText("PizzaMenu");
        jbtnPizzaMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPizzaMENUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jbtnEmployees)
                .addGap(52, 52, 52)
                .addComponent(jbtnCustomers)
                .addGap(52, 52, 52)
                .addComponent(jbtnOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jbtnDeliv, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jbtnPizzaMENU)
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(image6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEmployees)
                    .addComponent(jbtnCustomers)
                    .addComponent(jbtnOrders)
                    .addComponent(jbtnDeliv)
                    .addComponent(jbtnPizzaMENU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(image6, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrdersActionPerformed
        // TODO add your handling code here:
        OrderGUI poGUI = new OrderGUI();
        poGUI.show();
        dispose();
    }//GEN-LAST:event_jbtnOrdersActionPerformed

    private void jbtnDelivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDelivActionPerformed
        // TODO add your handling code here:
        DeliveryGUI dGUI = new DeliveryGUI();
        dGUI.show();
        dispose();
    }//GEN-LAST:event_jbtnDelivActionPerformed

    private void jbtnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmployeesActionPerformed
        // TODO add your handling code here:
        EmployeeGUI empGUI = new EmployeeGUI();
        empGUI.show();
        dispose();
        
    }//GEN-LAST:event_jbtnEmployeesActionPerformed

    private void jbtnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCustomersActionPerformed
        // TODO add your handling code here:
        CustomerGUI custGUI = new CustomerGUI();
        custGUI.show();
        dispose();
    }//GEN-LAST:event_jbtnCustomersActionPerformed

    private void jbtnPizzaMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPizzaMENUActionPerformed
        // TODO add your handling code here:
        PizzaMenu pm = new PizzaMenu();
        pm.show();
        dispose();
    }//GEN-LAST:event_jbtnPizzaMENUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton jbtnCustomers;
    private javax.swing.JButton jbtnDeliv;
    private javax.swing.JButton jbtnEmployees;
    private javax.swing.JButton jbtnOrders;
    private javax.swing.JButton jbtnPizzaMENU;
    // End of variables declaration//GEN-END:variables
}
