/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro.pizzarest;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import pro.pizzarest.HomePage2;

/**
 *
 * @author Hala Shakaa4
 */
public class OrderGUI extends javax.swing.JFrame {

    /**
     * Creates new form OrderGUI
     */
    public OrderGUI() {
        initComponents();
    
 setImage();

    }

    public void setImage(){
        ImageIcon icon1 =new ImageIcon(getClass().getResource("/images/pizza1.jpg"));
                Image img1 =icon1.getImage().getScaledInstance(image1.getWidth(), image1.getHeight(), Image.SCALE_SMOOTH);
        image1.setIcon(new ImageIcon(img1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnAddNewOrder = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaAllOrd = new javax.swing.JTextArea();
        jbtnAllOr = new javax.swing.JButton();
        jbtnGenerateReport = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jbtnPizzaOrder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtOrderID = new javax.swing.JTextField();
        jtxtCustID = new javax.swing.JTextField();
        jtxtOrderDate = new javax.swing.JTextField();
        jcomboOrderType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jbtnDeleteOrder = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnAddNewOrder.setBackground(new java.awt.Color(255, 153, 102));
        jbtnAddNewOrder.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnAddNewOrder.setText("Add New Order");
        jbtnAddNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNewOrderActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel7.setText("All Orders :");

        jtxtAreaAllOrd.setColumns(20);
        jtxtAreaAllOrd.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaAllOrd);

        jbtnAllOr.setBackground(new java.awt.Color(255, 153, 102));
        jbtnAllOr.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnAllOr.setText("Show All Orders");
        jbtnAllOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAllOrActionPerformed(evt);
            }
        });

        jbtnGenerateReport.setBackground(new java.awt.Color(255, 204, 153));
        jbtnGenerateReport.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnGenerateReport.setText("Generate Report");
        jbtnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateReportActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(204, 204, 204));
        jbtnBack.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnBack.setText("Go Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jbtnPizzaOrder.setBackground(new java.awt.Color(255, 204, 153));
        jbtnPizzaOrder.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnPizzaOrder.setText("Place an Order");
        jbtnPizzaOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPizzaOrderActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel1.setText("Order ID :");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel2.setText("Customer ID :");

        jLabel3.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel3.setText("Order Date :");

        jLabel5.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel5.setText("OrderType :");

        jtxtOrderID.setBackground(new java.awt.Color(204, 204, 204));

        jtxtCustID.setBackground(new java.awt.Color(204, 204, 204));

        jtxtOrderDate.setBackground(new java.awt.Color(204, 204, 204));
        jtxtOrderDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtOrderDateActionPerformed(evt);
            }
        });

        jcomboOrderType.setBackground(new java.awt.Color(204, 204, 204));
        jcomboOrderType.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jcomboOrderType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine-In", "Takeaway", "Delivery" }));
        jcomboOrderType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboOrderTypeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel9.setText("Address :");

        jtxtAddress.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 51, Short.MAX_VALUE)))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtCustID, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jtxtOrderDate)
                            .addComponent(jtxtAddress)
                            .addComponent(jtxtOrderID)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(jcomboOrderType, 0, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcomboOrderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(65, 65, 65))
        );

        jbtnDeleteOrder.setBackground(new java.awt.Color(255, 204, 153));
        jbtnDeleteOrder.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jbtnDeleteOrder.setText("Delete");
        jbtnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteOrderActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("Order Information System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jbtnPizzaOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(189, 189, 189)
                                .addComponent(jbtnDeleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnAllOr, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 214, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jbtnAddNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnAllOr, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jbtnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnAddNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDeleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPizzaOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddNewOrderActionPerformed
        try {
            // Register the PostgreSQL driver
        DriverManager.registerDriver(new org.postgresql.Driver());
        
        // Database connection details
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "hala";
        String up = "123456";
        
        // Establish the connection
        Connection con = DriverManager.getConnection(custr, un, up);
        con.setAutoCommit(false);
        
        // Get input values
        String orID = this.jtxtOrderID.getText();
        String cstID = this.jtxtCustID.getText();
        String orDate = this.jtxtOrderDate.getText();
      //  String dlvDT = this.jtxtDeliveryDT.getText();
        String orType = (String) this.jcomboOrderType.getSelectedItem();
        String address = ""; // Initialize address variable
        
        // Check if the order type is Delivery
        if ("Delivery".equalsIgnoreCase(orType)) {
            // If delivery, get the address from a text field or other input (assuming jtxtAddress here)
            address = this.jtxtAddress.getText();
            
            // Insert with Address into Order_ table
            String strStmt = "INSERT INTO Order_ VALUES (" + orID + ", " + cstID + ",CURRENT_TIMESTAMP , '" + orType + "', '" + address + "')";
            Statement stmt = con.createStatement();
            stmt.executeUpdate(strStmt);
            
            // Update Address in the Customer table
            String updateStmt = "UPDATE Customer SET \"Address\" = '" + address + "' WHERE CustomerID = " + cstID;
            stmt.executeUpdate(updateStmt);
        } else {
            // Insert without Address if not Delivery
            String strStmt = "INSERT INTO Order_ VALUES (" + orID + ", " + cstID + ", CURRENT_TIMESTAMP, '" + orType + "')";
            Statement stmt = con.createStatement();
            stmt.executeUpdate(strStmt);
        }
        
        // Commit the transaction
        con.commit();
        
        // Close the connection
        con.close();
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.toString());
    }
    }//GEN-LAST:event_jbtnAddNewOrderActionPerformed

    private void jcomboOrderTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboOrderTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboOrderTypeActionPerformed

    private void jbtnAllOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAllOrActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un="hala";
            String up="123456";
            Connection con= DriverManager.getConnection(custr, un, up);
            String sqlStr="select * from Order_ ";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(sqlStr);
            this.jtxtAreaAllOrd.setText("Order ID\tCust ID\tOrder Type\tOrder Date\t\tTotal Amount\n ");
           while( rs.next()){
              String oid= rs.getString(1);
              String cid= rs.getString("CustomerID");
              String od= rs.getString("OrderDate");
             // String dDT= rs.getString(4);
              String ot= rs.getString("OrderType");
              String ta= rs.getString("TotalAmount");
              this.jtxtAreaAllOrd.append(oid+"\t"+cid+"\t"+ ot+"\t"+od +"\t" + ta +"\n");
           }                           
            con.close();
            
        } catch (Exception ex) {
           // Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, ex.toString());
           
        }
    }//GEN-LAST:event_jbtnAllOrActionPerformed

    private void jbtnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateReportActionPerformed
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String url= "jdbc:postgresql://localhost:5432/postgres";
            String user="hala";
            String password="123456";
            Connection con= DriverManager.getConnection(url, user, password);
            InputStream inp= new FileInputStream(new File("Orders_P.jrxml"));
            JasperDesign jd= JRXmlLoader.load(inp);
            JasperReport jr= JasperCompileManager.compileReport(jd);
            JasperPrint jp= JasperFillManager.fillReport(jr, null, con);
  //        OutputStream os= new FileOutputStream(new File("rep.pdf"));
  //        JasperExportManager.exportReportToPdfStream(jp, os);
  //        os.close();
            JFrame frame = new JFrame("report");  
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);          
            con.close();
            inp.close();
            
        } catch (Exception ex) {
            //Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jbtnGenerateReportActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        HomePage2 hp = new HomePage2();
        hp.setVisible(true);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jbtnPizzaOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPizzaOrderActionPerformed
        // TODO add your handling code here:
        PizzaOrdersGUI poGUI = new PizzaOrdersGUI();
        poGUI.show();
        dispose();
    }//GEN-LAST:event_jbtnPizzaOrderActionPerformed

    private void jbtnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteOrderActionPerformed
        // TODO add your handling code here:
        try {
        // Register the PostgreSQL driver
        DriverManager.registerDriver(new org.postgresql.Driver());

        // Database connection details
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "hala";  // Your database username
        String up = "123456";  // Your database password

        // Establish the connection to the database
        Connection con = DriverManager.getConnection(custr, un, up);

        // Start a transaction to ensure both deletions are handled together
        con.setAutoCommit(false);

        // SQL statement to delete pizza orders based on the orderid
        String deletePizzaOrdersSQL = "DELETE FROM \"pizzaorders\" WHERE \"orderid\" = ?";  // Correct column name
        // SQL statement to delete the order from the Order_ table based on the orderid
        String deleteOrderSQL = "DELETE FROM \"order_\" WHERE \"orderid\" = ?";  // Correct column name

        // Get the OrderID from the user input (text field or other source)
        int orderID = Integer.parseInt(jtxtOrderID.getText());  // Assuming jtxtOrderID holds the order ID to delete

        // Prepare the SQL statements
        try (PreparedStatement pstmt1 = con.prepareStatement(deletePizzaOrdersSQL);
             PreparedStatement pstmt2 = con.prepareStatement(deleteOrderSQL)) {

            // Set the OrderID parameter for deleting related pizza orders
            pstmt1.setInt(1, orderID);
            pstmt1.executeUpdate();  // Execute the query to delete related pizza orders

            // Set the OrderID parameter for deleting the main order
            pstmt2.setInt(1, orderID);
            pstmt2.executeUpdate();  // Execute the query to delete the main order

            // Commit the transaction to finalize the deletion
            con.commit();

            // Show confirmation message to the user
            JOptionPane.showMessageDialog(null, "Order with ID " + orderID + " and its pizza orders have been deleted.");

        } catch (SQLException e) {
            // Rollback the transaction in case of error
            con.rollback();
            JOptionPane.showMessageDialog(null, "Error deleting order: " + e.getMessage());
            e.printStackTrace();
        }

        // Close the connection
        con.close();

    } catch (Exception ex) {
        // Handle any exceptions and show the error message
        JOptionPane.showMessageDialog(null, ex.toString());
    }
    }//GEN-LAST:event_jbtnDeleteOrderActionPerformed

    private void jtxtOrderDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtOrderDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtOrderDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAddNewOrder;
    private javax.swing.JButton jbtnAllOr;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnDeleteOrder;
    private javax.swing.JButton jbtnGenerateReport;
    private javax.swing.JButton jbtnPizzaOrder;
    private javax.swing.JComboBox<String> jcomboOrderType;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextArea jtxtAreaAllOrd;
    private javax.swing.JTextField jtxtCustID;
    private javax.swing.JTextField jtxtOrderDate;
    private javax.swing.JTextField jtxtOrderID;
    // End of variables declaration//GEN-END:variables
}
