/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro.pizzarest;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Hala Shakaa4
 */
public class PizzaOrdersGUI extends javax.swing.JFrame {

    /**
     * Creates new form PizzaOrdersGUI
     */
    public PizzaOrdersGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtOrderID = new javax.swing.JTextField();
        jtxtPizzaID = new javax.swing.JTextField();
        jComboBoxSize = new javax.swing.JComboBox<>();
        jtxtPrice = new javax.swing.JTextField();
        jtxtQuantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtTotalAmount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtnViewMenu = new javax.swing.JButton();
        jbtnAddPizzaOrder = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnTotalAmount = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Order ID :");

        jLabel4.setText("Pizza ID :");

        jLabel5.setText("Size :");

        jLabel6.setText("Quantity :");

        jLabel7.setText("Price :");

        jComboBoxSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));

        jLabel2.setText("Total Amount :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtxtOrderID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jtxtPizzaID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtQuantity)
                    .addComponent(jtxtPrice)
                    .addComponent(jtxtTotalAmount))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtPizzaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jtxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pizza Orders Details");

        jbtnViewMenu.setText("View Pizza Menu");
        jbtnViewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewMenuActionPerformed(evt);
            }
        });

        jbtnAddPizzaOrder.setText("Add pizza order");
        jbtnAddPizzaOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddPizzaOrderActionPerformed(evt);
            }
        });

        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnTotalAmount.setText("Total Amount");
        jbtnTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalAmountActionPerformed(evt);
            }
        });

        jButton1.setText("Generate Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnViewMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jbtnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnAddPizzaOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jbtnAddPizzaOrder)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnViewMenu)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBack)
                        .addGap(30, 30, 30)
                        .addComponent(jbtnTotalAmount)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddPizzaOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddPizzaOrderActionPerformed
        // TODO add your handling code here:
       try {
             // Check if any of the required fields are empty
        if (jtxtOrderID.getText().trim().isEmpty() || 
            jtxtPizzaID.getText().trim().isEmpty() ||
            jtxtQuantity.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;  // Stop execution if any required field is empty
        }

        // Set up the connection to the PostgreSQL database
        DriverManager.registerDriver(new org.postgresql.Driver());
        String url = "jdbc:postgresql://localhost:5432/postgres";
        String username = "hala";
        String password = "123456";
        Connection con = DriverManager.getConnection(url, username, password);
        con.setAutoCommit(false);

        // Parse input values
        int orderId = Integer.parseInt(jtxtOrderID.getText().trim());
        int pizzaId = Integer.parseInt(jtxtPizzaID.getText().trim());
        String size = jComboBoxSize.getSelectedItem().toString();
        int quantity = Integer.parseInt(jtxtQuantity.getText().trim());

        BigDecimal pricePerUnit;

        // Check if pizza is BBQ Chicken (pizzaId = 204) or a regular pizza
        if (pizzaId == 204) { 
            switch (size) {
                case "Small":
                    pricePerUnit = new BigDecimal("30.00");
                    break;
                case "Medium":
                    pricePerUnit = new BigDecimal("45.00");
                    break;
                case "Large":
                    pricePerUnit = new BigDecimal("60.00");
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Size not available.");
                    con.close();
                    return;
            }
        } else { 
            switch (size) {
                case "Small":
                    pricePerUnit = new BigDecimal("25.00");
                    break;
                case "Medium":
                    pricePerUnit = new BigDecimal("40.00");
                    break;
                case "Large":
                    pricePerUnit = new BigDecimal("55.00");
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Size not available.");
                    con.close();
                    return;
            }
        }

        // Calculate the total price for the quantity ordered
        BigDecimal totalPrice = pricePerUnit.multiply(new BigDecimal(quantity));
        jtxtPrice.setText(totalPrice.toString()); // Display the price in the UI

        // Step 4: Prepare and execute the SQL statement (Note: Exclude OrderPizzaID)
        String sql = "INSERT INTO PizzaOrders (OrderID, PizzaID, Size, Quantity, Price) VALUES ("
                + orderId + ", "
                + pizzaId + ", '"
                + size + "', "
                + quantity + ", "
                + totalPrice + ")";

        Statement stmt = con.createStatement();
        stmt.executeUpdate(sql);

        // Commit transaction
        con.commit();
        con.close();

        // Show success message
        JOptionPane.showMessageDialog(this, "The Order is added!");

        // Clear the fields for the next entry, except Order ID
        clearPizzaOrderFields();

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Please enter valid numbers for OrderID, PizzaID, and Quantity.");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "An error occurred while adding the order: " + ex.toString());
    }
}

// Method to clear the relevant fields except Order ID
private void clearPizzaOrderFields() {
    // Debugging print statement to ensure the method is called
    System.out.println("clearPizzaOrderFields called");

    // Clear all fields except the Order ID field
    jtxtPizzaID.setText("");      // Clear PizzaID field
    jtxtQuantity.setText("");     // Clear Quantity field
    jtxtPrice.setText("");        // Clear Price field
    
    // Reset the combo box selection to the default (first element)
    jComboBoxSize.setSelectedIndex(0);

    // Optional: Set focus back to the Pizza ID field for convenience
    jtxtPizzaID.requestFocus();
      
        
    }//GEN-LAST:event_jbtnAddPizzaOrderActionPerformed

    
    
    
    
    
    private void jbtnViewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewMenuActionPerformed
        // TODO add your handling code here:
        PizzaMenu pm = new PizzaMenu();
        pm.show();
        dispose();
    }//GEN-LAST:event_jbtnViewMenuActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        OrderGUI ogui = new OrderGUI();
        ogui.show();
        dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalAmountActionPerformed
        // TODO add your handling code here:
       try {
        if (jtxtOrderID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Order ID.");
            return;
        }

        int orderId = Integer.parseInt(jtxtOrderID.getText().trim());

        // Set up the connection
        DriverManager.registerDriver(new org.postgresql.Driver());
        String url = "jdbc:postgresql://localhost:5432/postgres";
        String username = "hala";
        String password = "123456";
        Connection con = DriverManager.getConnection(url, username, password);
// Calculate total amount for the order by summing the Price
        String sql = "SELECT SUM(Price) AS TotalAmount FROM PizzaOrders WHERE OrderID = ?";
        PreparedStatement pstmt = con.prepareStatement(sql);
        pstmt.setInt(1, orderId);
        ResultSet rs = pstmt.executeQuery();

        BigDecimal totalAmount = BigDecimal.ZERO;
        if (rs.next()) {
            totalAmount = rs.getBigDecimal("TotalAmount");

            if (totalAmount != null) {
                jtxtTotalAmount.setText(totalAmount.toString());
            } else {
                jtxtTotalAmount.setText("0.00");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No pizzas found for this Order ID.");
        }

        // Now update the TotalAmount column in the PizzaOrders table
        String updatePizzaOrdersSql = "UPDATE PizzaOrders SET TotalAmount = ? WHERE OrderID = ?";
        PreparedStatement updatePizzaOrdersPstmt = con.prepareStatement(updatePizzaOrdersSql);
        updatePizzaOrdersPstmt.setBigDecimal(1, totalAmount);
        updatePizzaOrdersPstmt.setInt(2, orderId);

        int rowsUpdatedPizzaOrders = updatePizzaOrdersPstmt.executeUpdate();

        if (rowsUpdatedPizzaOrders > 0) {
            JOptionPane.showMessageDialog(this, "Total amount updated successfully in PizzaOrders table.");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update TotalAmount in PizzaOrders table.");
        }

        // Update the TotalAmount in the Order_ table as well
        String updateOrderSql = "UPDATE Order_ SET TotalAmount = ? WHERE OrderID = ?";
        PreparedStatement updateOrderPstmt = con.prepareStatement(updateOrderSql);
        updateOrderPstmt.setBigDecimal(1, totalAmount);
        updateOrderPstmt.setInt(2, orderId);

        int rowsUpdatedOrder = updateOrderPstmt.executeUpdate();

        if (rowsUpdatedOrder > 0) {
            JOptionPane.showMessageDialog(this, "Total amount updated successfully in Order_ table.");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update TotalAmount in Order_ table.");
        }

        // Close resources
        rs.close();
        pstmt.close();
        updatePizzaOrdersPstmt.close();
        updateOrderPstmt.close();
        con.close();

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Please enter a valid Order ID.");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "An error occurred while calculating the total amount: " + ex.toString());
    }
    }//GEN-LAST:event_jbtnTotalAmountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String url= "jdbc:postgresql://localhost:5432/postgres";
            String user="hala";
            String password="123456";
            Connection con= DriverManager.getConnection(url, user, password);
            InputStream inp= new FileInputStream(new File("PizzaOrdersrep1.jrxml"));
            JasperDesign jd= JRXmlLoader.load(inp);
            JasperReport jr= JasperCompileManager.compileReport(jd);
            JasperPrint jp= JasperFillManager.fillReport(jr, null, con);
  //        OutputStream os= new FileOutputStream(new File("rep.pdf"));
  //        JasperExportManager.exportReportToPdfStream(jp, os);
  //        os.close();
            JFrame frame = new JFrame("report");  
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);          
            con.close();
            inp.close();
            
        } catch (Exception ex) {
            //Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaOrdersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaOrdersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaOrdersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaOrdersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaOrdersGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAddPizzaOrder;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnTotalAmount;
    private javax.swing.JButton jbtnViewMenu;
    private javax.swing.JTextField jtxtOrderID;
    private javax.swing.JTextField jtxtPizzaID;
    private javax.swing.JTextField jtxtPrice;
    private javax.swing.JTextField jtxtQuantity;
    private javax.swing.JTextField jtxtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
